version: 2.1
orbs:
  codecov: codecov/codecov@3.1.1
jobs:
  format: 
    docker:
        - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            sudo pip3 install -r requirements.txt
      - run:
          name: Sort Python imports
          command: |
            isort web_messaging/
      - run: 
          name: Check Pytho style
          command: |
            flake8 web_messaging/

  build_and_deploy:     
    docker:
        - image: google/cloud-sdk:slim
    steps:
      - checkout
      - run:
          name: Install Sphinx
          command: |
            apt install -y python-pip && \
            python3 -m pip install -r requirements.txt
      - run:
          name: Make Docs
          command: |
            cd docs && make html
      - run: 
          name: Deploy Docs
          command: |
            echo ${GCLOUD_SERVICE_KEY} > /tmp/sa_key.json
            gcloud auth activate-service-account --key-file=/tmp/sa_key.json
            rm /tmp/sa_key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet app deploy

workflows:
  version: 2.1
  format_and_test:
    jobs:
      - format
      - codecov/upload
      - build_and_deploy:
        filters:
          branches:
            only:
              - main